### ISSUE TITLE
Keyboard closes automatically after clearing text in App Drawer search bar

### ISSUE THREAD

**Issue by lupissc** [AxionAOSP/issue_tracker#27]
### ❗ What happened?

Hello Sir, I would like to report an issue. The keyboard in the App Drawer search bar automatically closes when all the typed text is deleted. This behavior is different from how keyboards usually work in search bars. Thank you!

https://github.com/user-attachments/assets/16f5721a-0286-4272-8d17-d34b4d2ecc4a

### 📱 Device Model

Redmi Note 8 Pro

### 🆕 AxionOS Version

1.3-NIGHTLY-20250418-OFFICIAL-GMS

### 📦 Are you using GApps?

Yes

### 📂 Is your device rooted?

No

### 🔄 Steps to Reproduce

1. Open search bar in App Drawer
2. Type and clear text in search bar

### 📜 Log Output

```shell

```

### ✅ Verification Checklist

- [x] 🔍 I have searched for existing issues and found none related to this bug.
- [x] 🔄 I have reproduced the issue after a clean install without modifying system files.
- [x] ⚙️ I have tested with different configurations (e.g., GApps/no GApps, rooted/non-rooted).
- [x] 📎 I have attached all necessary logs and provided reproduction steps.

**Comment by rmp22** [comment]
fixed by: https://github.com/AxionAOSP/android_packages_apps_Launcher3/commit/d5fa6a3373ef5d5072bc17e0a020b6a68e619451

**Comment by lupissc** [comment]
Tested on 20250506 build. Fixed. Thank you!

**Comment by lupissc** [comment]
Tested on axion-2.0-BETA-20250803 build, the issue is back. Thanks
